### ISSUE TITLE
Possible Packages and Assets

### ISSUE THREAD

**Issue by sh-biswas** [MLH-Fellowship/Evil-in-Jaffar#2]
**Is your feature request related to a problem? Please describe.**
We also need to decide the packages, assets, and sprites to use. 

**Describe the solution you'd like**
Here are some potential ones I found:

 - [2D Game Kit](https://assetstore.unity.com/packages/essentials/tutorial-projects/2d-game-kit-107098)
 - [Fantasy Characters](https://assetstore.unity.com/packages/2d/characters/fantasy-character-free-pack-147995)
 - [Free 2D Mega Pack by Brackeys](https://assetstore.unity.com/packages/2d/free-2d-mega-pack-177430)
 - [2D Fantasy Character Pack](https://assetstore.unity.com/packages/2d/characters/2d-fantasy-character-pack-demo-101030)
 - [Free Assets List by Brackeys](https://assetstore.unity.com/lists/v2-87803?aid=1101lPGj&utm_source=aff)
 - [Student Snaps bundle free from Unity](https://assetstore.unity.com/browse/student-plan-pack)
 - [Playmaker](https://assetstore.unity.com/packages/tools/visual-scripting/playmaker-368?_ga=2.182671269.2097987072.1602955542-697581557.1602955542)

The last one is actually not a free package, but a lot of big games used it. We can maybe find similar packages, as it comes with a lot of elements. 

**Describe alternatives you've considered**
Drop any packages or backgrounds or assets you think would be good for this project!

**Additional context**
We can finalize the list and start working on the scenes.

**Comment by sh-biswas** [comment]
Possible Packages:
- [Megapack III](https://assetstore.unity.com/packages/2d/characters/aekashics-librarium-megapack-iii-130410) 
- [Knight Sprite Sheet](https://assetstore.unity.com/packages/2d/characters/knight-sprite-sheet-free-93897)

**Comment by sh-biswas** [comment]
Import different characters and use Game Kit Ellen to make imported character main character

**Comment by sh-biswas** [comment]
[Dragon Warrior](https://assetstore.unity.com/packages/2d/characters/dragon-warrior-free-93896)

**Comment by sh-biswas** [comment]
[2D Fantasy Demon Sprites](https://assetstore.unity.com/packages/2d/characters/2d-fantasy-demon-sprites-63159)

**Comment by sh-biswas** [comment]
[Electric Mage](https://assetstore.unity.com/packages/2d/characters/electric-mage-2d-character-179451)

**Comment by sh-biswas** [comment]
[Maybe for background?](https://assetstore.unity.com/packages/2d/environments/hq-magical-world-the-wizard-s-tower-152756)

**Comment by sh-biswas** [comment]
[Fantasy Monsters: Character Editor](https://assetstore.unity.com/packages/2d/characters/fantasy-monsters-character-editor-pro-100192)

**Comment by sh-biswas** [comment]
[Fantasy Monsters Animated](https://assetstore.unity.com/packages/2d/characters/fantasy-monsters-animated-159572)

**Comment by sh-biswas** [comment]
[Free 2D Orcs Sprite Sheets](https://free-game-assets.itch.io/free-2d-orcs-sprite-sheets)

**Comment by V2dha** [comment]
> [Maybe for background?](https://assetstore.unity.com/packages/2d/environments/hq-magical-world-the-wizard-s-tower-152756)

I really like this one but I don't think its free :(

**Comment by V2dha** [comment]
@sksuryan @sh-biswas  [Hero Knight](https://assetstore.unity.com/packages/2d/characters/hero-knight-pixel-art-165188)

Look at this asset for the hero character and villains and it is free

**Comment by sh-biswas** [comment]
> @sksuryan @sh-biswas [Hero Knight](https://assetstore.unity.com/packages/2d/characters/hero-knight-pixel-art-165188)
> 
> Look at this asset for the hero character and villains and it is free

I like this one, but are we fine with pixelated art? also does it come with animations?

**Comment by sh-biswas** [comment]
> @sksuryan @sh-biswas [Hero Knight](https://assetstore.unity.com/packages/2d/characters/hero-knight-pixel-art-165188)
> 
> Look at this asset for the hero character and villains and it is free

Actually it seems that only the knight is free and not the other assets in the same package

**Comment by sh-biswas** [comment]
Maybe we can do these together? 
 - [Dark wizard](https://assetstore.unity.com/packages/2d/characters/evil-wizard-168007)
 - [Monsters](https://assetstore.unity.com/packages/2d/characters/monsters-creatures-fantasy-167949)

**Comment by V2dha** [comment]
Final Packages for protagonists and villains -

[Hero Knight](https://assetstore.unity.com/packages/2d/characters/hero-knight-pixel-art-165188#content) - Saurabh
[Monsters](https://assetstore.unity.com/packages/2d/characters/monsters-creatures-fantasy-167949) - Shilpita
[Bandits](https://assetstore.unity.com/packages/2d/characters/bandits-pixel-art-104130) - Vividha
