### ISSUE TITLE
Game Name

### ISSUE THREAD

**Issue by sh-biswas** [MLH-Fellowship/Evil-in-Jaffar#3]
**Is your feature request related to a problem? Please describe.**
We need a name for our game, as I expect Kunal will ask for one at our next standup.

**Describe the solution you'd like**
Please drop any ideas you have in the comments! I haven't come up with any so far.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sh-biswas** [comment]
Evil in Jaffar

**Comment by V2dha** [comment]
I like the name!

**Comment by sksuryan** [comment]
+1
