### ISSUE TITLE
Skeleton Death Animation Continues to Loop

### ISSUE THREAD

**Issue by sh-biswas** [MLH-Fellowship/Evil-in-Jaffar#5]
**Describe the bug**
The skeleton death animation continues to loop even though the animation should only place once. I referenced the heavy bandit animator and copied that using the skeleton sprites, but it still rearranges and dies again. 

**To Reproduce**
1. Pull 'transitions' branch
2. Play skeleton scene and kill skeleton enemy using controls.

**Expected behavior**
Skeleton death should just happen once. 

**Screenshots**
Here is a screen recording of the behavior

[Screen Recording 2020-10-25 at 2.32.36 PM.zip](https://github.com/MLH-Fellowship/fantasy-game/files/5436005/Screen.Recording.2020-10-25.at.2.32.36.PM.zip)

**Comment by sksuryan** [comment]
Fixed
