### ISSUE TITLE
Player does not take damage in Skeleton Scene

### ISSUE THREAD

**Issue by sh-biswas** [MLH-Fellowship/Evil-in-Jaffar#6]
**Describe the bug**
In the skeleton scene, I reimplemented the exact behavior of the heavy bandit(including copy-pasting the HeroKnight prefab from that scene), but it seems that the player doesn't take any damage from the skeleton enemy. I couldn't find the issue. 

**To Reproduce**
1. Pull 'attacks' branch.
2. Play skeleton scene and let skeleton attack HeroKnight.

**Expected behavior**
Player should take damage from skeleton enemy.

**Screenshots**
Here is a screen recording.
[Screen Recording 2020-10-25 at 2.38.11 PM.zip](https://github.com/MLH-Fellowship/fantasy-game/files/5436008/Screen.Recording.2020-10-25.at.2.38.11.PM.zip)

**Comment by sksuryan** [comment]
Fixed

**Comment by sh-biswas** [comment]
Ah shoot, I should've put the transitions branch instead of attack branch. I guess we can just demo the transitions branch today and merge the two later.

**Comment by sksuryan** [comment]
Yupppp
